telegram:
  web:
    bot-username: cookassistbot
    admin-chat-id: 1026435138
    auth:
      token: ${WEB_TELEGRAM_AUTH_TOKEN}
  swearing:
    is_enabled: true
    path: src/main/resources/telegram/swearing.txt
    reply: |
      Слыш петушара ебаная, ты за базаром следи, шнырь чмошный. Список ингредиентов прислал сюда, пернатый, я тебе список блюд в ответ. Вперед ебать.