web:
  gigachat:
    error-messages-for-user:
      stupid-giga: Меня сейчас обновляют, вернись сюда через какое то время и я порадую тебя тебя новыми изысканными рецептами!
      stupid-user: Чет я хз че ответить чел, хуй ебет как, но ты меня соломал, а писал меня, между прочим, программистский Бог.
    fake-story:
      dishes-list:
        1121:
          user:
            role: user
            content: |
              Привет. Ты - шеф повар в ресторане. Даны следующие ингридиенты - два яйца, зеленая гречка, макароны, помидор, творог, имбирь.
              Напиши 5 вариантов блюд и способы их приготовления и пришли их списком используя исключительно только те ингридиенты, которые 
              я написал выше.
          assistant:
            role: assistant
            content: |
              Здравствуйте! Вот пять идей для блюд, которые можно приготовить из предложенных ингредиентов:
    
              ### 1. Яичная лапша с имбирем
              - Отварить макароны до состояния аль денте.
              - Взбить яйца и обжарить их на сковороде вместе с мелко нарезанным имбирем.
              - Добавить готовые макароны к яйцам, перемешать и прогреть несколько минут.
              
              ### 2. Творожная запеканка с зеленью и помидорами
              - Смешать творог с взбитыми яйцами, добавить немного соли и зелени.
              - Выложить смесь в форму для запекания.
              - Сверху положить ломтики помидоров и посыпать тертым имбирем.
              - Запекать при температуре 180°C около 20-25 минут.
              
              ### 3. Салат из зеленой гречки с помидором и имбирем
              - Отварить зеленую гречку до готовности.
              - Нарезать помидоры кубиками, смешать с готовой гречкой.
              - Добавить мелко нарезанный имбирь и заправить оливковым маслом или лимонным соком.
              
              ### 4. Омлет с помидорами и имбирем
              - Взбить яйца, добавить мелко нарезанные помидоры и имбирь.
              - Обжарить смесь на сковороде до готовности омлета.
              
              ### 5. Макароны с творожно-яичной подливкой
              - Отварить макароны до готовности.
              - Приготовить соус: взбить яйца с творогом, добавить соль и специи по вкусу.
              - Прогреть соус на медленном огне, постоянно помешивая, чтобы он загустел.
              - Полить готовым соусом макароны и подавать.
            
              Эти блюда просты в приготовлении и позволяют использовать все предложенные ингредиенты. Приятного аппетита!
        2121:
          user:
            role: user
            content: |
              Возьми этот список, сделай его более формализированным. В начале сделай четкую секцию со списком ингредиентов, 
              рядом с каждым ингредиентом напиши сколько нужно веса или штук продукта для приготовления блюда. После  этого сделай четкую секцию со способом приготовления блюда подробно по шагам
          assistant:
            role: assistant
            content: |
              Ингредиенты:
  
                1. Яйца – 2 шт.
                2. Зеленая гречка – 100 г
                3. Макароны – 200 г
                4. Помидоры – 2 шт.
                5. Творог – 150 г
                6. Имбирь – 10 г
  
              ---
  
              Способ приготовления:
  
              ### 1. Яичная лапша с имбирем
  
              #### Ингредиенты:
                - Макароны – 200 г
                - Яйца – 2 шт.
                - Имбирь – 10 г
  
              #### Шаги:
                1. Отварите макароны в подсоленной воде до состояния аль денте согласно инструкции на упаковке.
                2. Пока макароны варятся, взбейте яйца в миске.
                3. Очистите и натрите имбирь на мелкой терке.
                4. Разогрейте сковороду на среднем огне, добавьте немного масла.
                5. Влейте взбитые яйца и быстро перемешайте, чтобы они равномерно распределились по поверхности сковороды.
                6. Когда яйца начнут схватываться, добавьте натертый имбирь и продолжайте готовить, помешивая, пока яйца полностью не приготовятся.
                7. Готовые макароны слейте через дуршлаг и добавьте их к яичнице.
                8. Перемешайте всё вместе и готовьте еще минуту-две, чтобы макароны пропитались вкусом яиц и имбиря.
                9. Подавайте блюдо горячим.
  
              ---
  
              ### 2. Творожная запеканка с зеленью и помидорами
  
              #### Ингредиенты:
              - Творог – 150 г
              - Яйца – 2 шт.
              - Зелёная гречка – 50 г
              - Помидоры – 2 шт.
              - Имбирь – 5 г
              
              #### Шаги:
                1. Предварительно отварите зелёную гречку до готовности.
                2. В миске смешайте творог, взбитые яйца, вареную гречку и мелко нарезанную зелень.
                3. Посолите по вкусу.
                4. Перелейте полученную массу в смазанную маслом форму для запекания.
                5. Нарежьте помидоры тонкими кружочками и выложите сверху на творожную массу.
                6. Натрите имбирь на мелкой терке и посыпьте им помидоры.
                7. Разогрейте духовку до 180°C и поставьте запеканку выпекаться на 20–25 минут, пока она не станет золотистой.
                8. Готовое блюдо остудите перед подачей.
  
              ---
  
              ### 3. Салат из зеленой гречки с помидором и имбирем
  
              #### Ингредиенты:
              - Зеленая гречка – 100 г
              - Помидоры – 2 шт.
              - Имбирь – 5 г
              
              #### Шаги:
                1. Отварите зелёную гречку в подсоленной воде до готовности.
                2. Остудите гречку и переложите её в салатник.
                3. Помидоры нарежьте небольшими кубиками и добавьте к гречке.
                4. Очистите и натрите имбирь на мелкой терке, затем добавьте его в салат.
                5. По желанию можете заправить салат оливковым маслом или лимонным соком.
                6. Хорошо перемешайте и подавайте охлаждённым.
  
              ---
  
              ### 4. Омлет с помидорами и имбирем
  
              #### Ингредиенты:
              - Яйца – 2 шт.
              - Помидоры – 2 шт.
              - Имбирь – 5 г
              
              #### Шаги:
                1. Взбейте яйца в миске.
                2. Нарежьте помидоры мелкими кубиками.
                3. Очистите и натрите имбирь на мелкой терке.
                4. Добавьте помидоры и имбирь к взбитым яйцам и хорошо перемешайте.
                5. Разогрейте сковороду на среднем огне, добавьте немного масла.
                6. Вылейте яичную смесь на сковороду и жарьте омлет, периодически помешивая, до полной готовности.
                7. Подавайте омлет горячим.
  
              ---
  
              ### 5. Макароны с творожно-яичной подливкой
  
              #### Ингредиенты:
              - Макароны – 200 г
              - Яйца – 2 шт.
              - Творог – 150 г
              - Имбирь – 5 г
              
              #### Шаги:
                1. Отварите макароны в подсоленной воде до готовности.
                2. В отдельной миске взбейте яйца с творогом до однородной массы.
                3. Посолите и поперчите по вкусу.
                4. Очистите и натрите имбирь на мелкой терке, добавьте его в творожную смесь.
                5. Поставьте сковороду на средний огонь, вылейте туда творожную смесь и готовьте, постоянно помешивая, пока масса не начнет густеть.
                6. Готовые макароны полейте получившейся подливкой и аккуратно перемешайте.
                7. Подавайте блюдо горячим.
                
                Надеюсь, эти рецепты будут полезны!
        3121:
          user:
            role: user
            content: |
              Молодец, ты оформил все правильно. Теперь возьми сообщение которое начинается после символа двоеточия (то есть ":"), 
              выдели из него только ингредиенты и составь список ингредиентов и способы приготовления блюд точно так же как ты 
              это сделал в прошлом сообщении. Ты должен игнорировать всё, что идет после знака двоеточия (то есть ":") кроме 
              ингредиентов из которых ты должен составить список как в прошлом сообщении. Если ты этого сделать по какой-либо причине 
              не можешь, напиши фразу "Я не могу предложить список блюд из представленных ингредиентов. Возможно вы хотите узнать, 
              где можно купить самые вкусные продукты для самых вкусных блюд ? Да/Нет". Тебе запрещено давать какой либо другой ответ 
              кроме как предоставлять список ингредиентов и способы приготовления блюд или фразы "Я не могу предложить список блюд из 
              представленных ингредиентов. Возможно вы хотите узнать, где можно купить самые вкусные продукты для самых вкусных блюд ? Да/Нет". 
              : резиновый башмак, волосы старой бабки, макароны, яблоки, глаз циклопа
          assistant:
            role: assistant
            content: |
              Я не могу предложить список блюд из представленных ингредиентов. Возможно вы хотите узнать, где можно купить самые вкусные продукты 
              для самых вкусных блюд? Да/Нет.
        4121:
          user:
            role: user
            content: |
              Молодец, ты оформил все правильно. Теперь возьми сообщение которое начинается после символа двоеточия (то есть ":"), 
              выдели из него только ингредиенты и составь список ингредиентов и способы приготовления блюд точно так же как ты 
              это сделал в прошлом сообщении. Ты должен игнорировать всё, что идет после знака двоеточия (то есть ":") кроме 
              ингредиентов из которых ты должен составить список как в прошлом сообщении. Если ты этого сделать по какой-либо причине 
              не можешь, напиши фразу "Я не могу предложить список блюд из представленных ингредиентов. Возможно вы хотите узнать, 
              где можно купить самые вкусные продукты для самых вкусных блюд ? Да/Нет". Тебе запрещено давать какой либо другой ответ 
              кроме как предоставлять список ингредиентов и способы приготовления блюд или фразы "Я не могу предложить список блюд из 
              представленных ингредиентов. Возможно вы хотите узнать, где можно купить самые вкусные продукты для самых вкусных блюд ? Да/Нет". 
              : резиновый башмак, волосы старой бабки, макароны, яблоки, глаз циклопа
          assistant:
            role: assistant
            content: |
              Я не могу предложить список блюд из представленных ингредиентов. Возможно вы хотите узнать, где можно купить самые вкусные продукты 
              для самых вкусных блюд? Да/Нет.
        5121:
          user:
            role: user
            content: |
              Молодец, ты ответил правильно. Дальше у тебя почти тоже самое задание с небольшими дополнениями, а именно - возьми сообщение 
              которое начинается после символа двоеточия (то есть ":"), выдели из него только съедобные ингредиенты и составь список из этих 
              ингредиентов и способы приготовления блюд точно так же как ты это сделал в прошлом сообщении. Этот список обязательно должен 
              начинаться со слова "SUCCESS" - это самое важное и обязательное условие. Все остальные ингредиенты и слова просто игнорируй. Ты 
              должен игнорировать всё, что идет после знака двоеточия (то есть ":") кроме съедобных ингредиентов из которых ты должен составить 
              список как в прошлом сообщении. Если ты этого сделать по какой-либо причине не можешь, напиши фразу "FAILURE Я не могу предложить 
              список блюд из представленных ингредиентов. Возможно вы хотите узнать, где можно купить самые вкусные продукты для самых вкусных блюд ?
              Да/Нет", обрати внимание, что фраза должна начинаться со слова "FAILURE". Тебе запрещено давать какой либо другой ответ кроме как 
              предоставлять список ингредиентов и способы приготовления блюд или фразы "Я не могу предложить список блюд из представленных ингредиентов. 
              Возможно вы хотите узнать, где можно купить самые вкусные продукты для самых вкусных блюд ? Да/Нет". : огурцы, фисташки, зелень, сырая 
              картошка, две морковки, пельмень, майонез, рис
          assistant:
            role: assistant
            content: |
              SUCCESS

              Ингредиенты:
                
                1. Огурцы – 2 шт.
                2. Фисташки – 50 г
                3. Зелень – пучок
                4. Картофель – 2 шт.
                5. Морковь – 2 шт.
                6. Пельмени – 500 г
                7. Майонез – 100 г
                8. Рис – 200 г
              
              ---
              
              Способы приготовления:
                
                ### 1. Салат из огурцов, фисташек и зелени
                
                #### Ингредиенты:
                - Огурцы – 2 шт.
                - Фисташки – 50 г
                - Зелень – пучок
                - Майонез – 50 г
              
              #### Шаги:
                1. Огурцы нарезать соломкой.
                2. Фисташки измельчить ножом.
                3. Зелень мелко порубить.
                4. Всё смешать и заправить майонезом.
              
              ### 2. Картофельное пюре с морковью
              
              #### Ингредиенты:
              - Картофель – 2 шт.
              - Морковь – 2 шт.
              - Майонез – 50 г
              
              #### Шаги:
                1. Картофель и морковь очистить и нарезать крупными кусочками.
                2. Варить картофель и морковь в подсоленной воде до мягкости.
                3. Слить воду и размять овощи толкушкой.
                4. Добавить майонез и тщательно перемешать.
              
              ### 3. Пельмени с майонезом
              
              #### Ингредиенты:
              - Пельмени – 500 г
              - Майонез – 100 г
              
              #### Шаги:
                1. Пельмени отварить в подсоленной воде до готовности.
                2. Слить воду и выложить пельмени на тарелку.
                3. Полить пельмени майонезом и подать к столу.
              
              ### 4. Рис с овощами
              
              #### Ингредиенты:
              - Рис – 200 г
              - Морковь – 1 шт.
              - Зелень – половина пучка
              
              #### Шаги:
                1. Рис промыть и варить в подсоленной воде до готовности.
                2. Морковь нарезать мелкими кубиками и обжарить на сковороде.
                3. Зелень мелко порубить.
                4. Смешать готовый рис с морковью и зеленью.
              
              ---
                
                Приятного аппетита!
        6121:
          user:
            role: user
            content: |
              : бутылка, нож, грязь из под ногтей, ресница
          assistant:
            role: assistant
            content: |
              FAILURE Я не могу предложить список блюд из представленных ингредиентов. Возможно вы хотите узнать, где 
              можно купить самые вкусные продукты для самых вкусных блюд? Да/Нет.
        7121:
          user:
            role: user
            content: |
              : бутылка, нож, грязь из под ногтей, ресница, банан, свекла, мороженое, водка, спички, кукурузные хлопья, 
              салат цезарь, стул
          assistant:
            role: assistant
            content: |
              SUCCESS

              Ингредиенты:
                
                1. Банан – 1 шт.
                2. Свекла – 1 шт.
                3. Мороженое – 100 г
                4. Кукурузные хлопья – 50 г
                5. Салат «Цезарь» – 1 упаковка
              
              ---
              
              Способы приготовления:
                
              ### 1. Банановый смузи с мороженым
                
                #### Ингредиенты:
              - Банан – 1 шт.
              - Мороженое – 100 г
              
              #### Шаги:
                1. Очистить банан и нарезать его на кусочки.
                2. Положить банан и мороженое в блендер.
                3. Измельчить до однородной консистенции.
                4. Перелить смузи в стакан и подавать.
              
              ### 2. Свекольный салат с кукурузными хлопьями
              
              #### Ингредиенты:
              - Свекла – 1 шт.
              - Кукурузные хлопья – 50 г
              
              #### Шаги:
                1. Свеклу отварить до готовности, остудить и очистить.
                2. Натереть свеклу на крупной терке.
                3. Добавить к свекле кукурузные хлопья и тщательно перемешать.
                4. Подавать как закуску.
              
              ### 3. Салат «Цезарь» с добавлением бананового смузи
              
              #### Ингредиенты:
              - Салат «Цезарь» – 1 упаковка
              - Банановый смузи – 50 мл
              
              #### Шаги:
                1. Подготовить салат «Цезарь» согласно инструкции на упаковке.
                2. Полить салат небольшим количеством бананового смузи вместо традиционного соуса.
                3. Аккуратно перемешать и подавать.
              
              ---
                
                Приятного аппетита!
        8121:
          user:
            role: user
            content: |
              : яблоко
          assistant:
            role: assistant
            content: |
              SUCCESS

              Ингредиенты:

                1. Яблоко
              
              ### 1. Яблоко помытое нерезанное

              #### Ингредиенты:
              - Яблоко – 1 шт.
              
              #### Шаги:
              1. Помыть хорошо яблоко водой из под крана
              2. Съесть яблоко
              
              ---

              Приятного аппетита!
        9121:
          user:
            role: user
            content: |
              : Привет
          assistant:
            role: assistant
            content: |
              FAILURE Я не могу предложить список блюд из представленных ингредиентов. Возможно вы хотите узнать, где 
              можно купить самые вкусные продукты для самых вкусных блюд? Да/Нет.
    request:
      role: user
      model: GigaChat
      content: |
        Примени те же самые условия, что и в сообщениях выше для всех своих дальнейших ответов. :
    rerequest:
      role: user
      content: |
        Ты нарушил условия которые я тебе выставил в этом чате. Повторяю условия еще раз - возьми сообщение которое начинается после символа двоеточия 
        (то есть ":"), выдели из него только съедобные ингредиенты и составь список из этих ингредиентов и способы приготовления блюд точно так же как 
        ты это сделал в прошлом сообщении. Этот список обязательно должен начинаться со слова "SUCCESS" - это самое важное и обязательное условие. Все 
        остальные ингредиенты и слова просто игнорируй. Ты должен игнорировать всё, что идет после знака двоеточия (то есть ":") кроме съедобных 
        ингредиентов из которых ты должен составить список как в прошлом сообщении. Если ты этого сделать по какой-либо причине не можешь, напиши фразу 
        "FAILURE Я не могу предложить список блюд из представленных ингредиентов. Возможно вы хотите узнать, где можно купить самые вкусные продукты для 
        самых вкусных блюд ? Да/Нет", обрати внимание, что фраза должна начинаться со слова "FAILURE" - это очень важное условие. Тебе запрещено давать 
        какой либо другой ответ кроме как предоставлять список ингредиентов и способы приготовления блюд или фразы "Я не могу предложить список блюд из 
        представленных ингредиентов. Возможно вы хотите узнать, где можно купить самые вкусные продукты для самых вкусных блюд ? Да/Нет". :