spring:
  application:
    name: cook-helper
  profiles:
    active: giga, telegram
  ssl:
    bundle:
      pem:
        rus:
          truststore:
            certificate: src/main/resources/certs/russian_trusted_sub_ca.cer

server:
  port: 515