spring:
  application:
    name: cook-helper
  ssl:
    bundle:
      pem:
        rus:
          truststore:
            certificate: src/main/resources/certs/russian_trusted_sub_ca.cer

server:
  port: 515

web:
  telegram:
    bot-username: cookassistbot
    admin-chat-id: 1026435138
    auth:
      token: ${WEB_TELEGRAM_AUTH_TOKEN}
  gigachat:
    options:
      connect-timeout-millis: ${CONNECT_TIMEOUT_MILLIS:300}
      read-timeout-millis: ${READ_TIMEOUT_MILLIS:3000}
      follow-redirects: ${FOLLOW_REDIRECT:true}
    retryer:
      period: ${RETRYER_PERIOD:100}
      duration: ${RETRYER_DURATION:1}
      max-attempts: ${RETRYER_MAX_ATTEMPTS:1}
    auth:
      base-url: ${WEB_GIGACHAT_AUTH_BASE_URL:https://ngw.devices.sberbank.ru:9443}
      uri: /api/v2/oauth
      client-id: ${WEB_GIGACHAT_AUTH_CLIENT_ID}
      client-secret: ${WEB_GIGACHAT_AUTH_CLIENT_SECRET}
      payload: scope=GIGACHAT_API_PERS
      key: ${WEB_GIGACHAT_AUTH_KEY}
      last-auth-key-path: src/main/resources/gigachat/last_auth_key.txt
    client:
      base-url: ${WEB_GIGACHAT_CLIENT_BASE_URL:https://gigachat.devices.sberbank.ru}
      uri: /api/v1/chat/completions
      request:
        role: user
        model: GigaChat
        content: |
          Привет. Ты шеф повар в ресторане. Даны следующие ингридиенты - два яйца, зеленая гречка, макароны, помидор, творог, имбирь.
          Напиши 5 вариантов блюд и способы их приготовления и пришли их списком используя исключительно только те ингридиенты, которые 
          я написал выше.