package ru.seraleu.telegram.users;

public enum TelegramCommunicationStep {
    DISHES_BUTTON_PUSHED,
    SLOVOTBIRATOR_REQUEST,
    SLOVOTBIRATOR_RESPONSE,
    DISHES_REQUEST,
    DISHES_RESPONSE,
    STUPID_USER_RESPONSE,
    STUPID_GIGA_RESPONSE,
    NO_RESPONSE,
    EXCEPTION_RESPONSE
}
